const SUPABASE_URL = 'https://gdfwqciireebkhrpwchn.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkZndxY2lpcmVlYmtocnB3Y2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0ODMyMzEsImV4cCI6MjA4MjA1OTIzMX0.h6K2znKvdf-ypjC6Lotg8Cyzbc2yWp_t_Tx3ouIhsSg'

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);